const sampleData = {
  products: [
    {
      name: "پیراهن پولو مردانه",
      slug: "polo-sporting-stretch-shirt",
      category: "پیراهن مردانه",
      description: "Classic Polo style with modern comfort",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 880000,
      brand: "پولو",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "پیراهن آستین بلند کشی بروکس برادرز",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "پیراهن مردانه",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 1650000,
      brand: "بروکس برادرز",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "پیراهن کلاسیک مردانه تامی",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "پیراهن مردانه",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 2180000,
      brand: "تامی",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "پیراهن تمام نخ کالوین کلین",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "پیراهن مردانه",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 1980000,
      brand: "کالوین کلین",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "پیراهن پولو اکسفورد",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "پیراهن مردانه",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 2450000,
      brand: "پولو",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "هودی صورتی کلاسیک پولو",
      slug: "polo-classic-pink-hoodie",
      category: "سوییشرت مردانه",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 2980000,
      brand: "پولو",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: "هودی کلاسیک پولو",
      slug: "polo-classic-hoodie",
      category: "هودی مردانه",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p7-1.jpg",
        "/images/sample-products/p7-2.jpg",
      ],
      price: 3100000,
      brand: "پولو",
      rating: 4.7,
      numReviews: 19,
      stock: 4,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
